#ifndef BORC_H
#define BORC_H

#include "Fighter.h"

/*
Class: Borc
Author: Callum M

Purpose:
    -Borc is a derivative of fighter, so it moves the same way as the rest of the fighters, with the only difference being the strength value
     generated by the constructor

Data Members:
    -Borc contains all the data members inherited from Fight and Character, and as such needs no new ones

Member Functions:
    -Borc(int,int)
        -The default constructor to create a borc with limits specified from the parameters

*/

class Borc:public Fighter
{
    public:
    Borc(int=0,int=0);

};




#endif